### PR TITLE
Pendulum: make PendulumState as subtype of AbstractArray

### PR DESCRIPTION
**Pull request by lilanger**
- added state() to import/export
- changed state from PendulumState type to array (easier to handle in advanced algorithms)
- shortened action annotation in plot

### CODE REVIEW

**Comment by iblislin** [comment]
> changed state from PendulumState type to array (easier to handle in advanced algorithms)

How about keep `PendulumState` presented but just subtyped it from `Vector{Float}`, do this way help you handle in your algo?
(Or solution 2: wirte some `convert` function for it.)

**Comment by lilanger** [comment]
It would be essential that env.state returns an Array instead of a PendulumState. I don't know how to do the subtyping though, I tried something like this but this is not valid:
````julia
mutable struct PendulumState{T<:Float64} <: Vector{Float64}
  θ::T
  θvel::T
  PendulumState(θ, θvel) = Float64[θ, θvel]
end

mutable struct Pendulum <: AbstractEnvironment
  state::Vector{Float64}
  reward::Float64
  a::Float64 # last action for rendering
  steps::Int
  maxsteps::Int
end

**Comment by iblislin** [comment]
ah, I guess the `AbstractVector` is the legit one.

**Comment by lilanger** [comment]
Nice, yes this seems to work.

**Comment by iblislin** [comment]
could you test the new patch?

**Pull request merged**
