### PR TITLE
Drop v0.7 support and introduce Project.toml

### PR DESCRIPTION
**Pull request by iblislin**

### CODE REVIEW

**Comment by iblislin** [comment]
@felixchalumeau where is the actual changelog of LearnBase.jl ?

**Comment by felixchalumeau** [comment]
> @felixchalumeau where is the actual changelog of LearnBase.jl ?

@iblis17 I don't know

**Comment by iblislin** [comment]
okay, I tried to upgrade it. Please try this branch out.

**Comment by felixchalumeau** [comment]
> okay, I tried to upgrade it. Please try this branch out.

ok, I just tried the branch, it seems to work much better !

Also, I was wandering if it would be better to add "Plots" in the dependencies, as it is used in examples/moutain_car.jl ?

**Comment by iblislin** [comment]
> Also, I was wandering if it would be better to add "Plots" in the dependencies, as it is used in examples/moutain_car.jl ?

well, I won't add it. We already have "RecipesBase" as a dep for package source.
If you want to make example better, I suggest the style like Flux model-zoo: creating a `Project.toml` for each examples.
e.g: https://github.com/FluxML/model-zoo/tree/master/vision/cdcgan_mnist

**Comment by iblislin** [comment]
I'm going to register this version.

**Comment by felixchalumeau** [comment]
> well, I won't add it. We already have "RecipesBase" as a dep for package source.

Ok, got it ! 

> If you want to make example better, I suggest the style like Flux model-zoo: creating a `Project.toml` for each examples.
> e.g: https://github.com/FluxML/model-zoo/tree/master/vision/cdcgan_mnist

Ok ! Just getting use to julia and more precisely Reinforce.jl and Flux.jl at the moment but it will a pleasure to work on this later!

In any case, thanks for the quick reaction to fix this little issue.

**Pull request merged**
